const STATUS_NOT_FOUND = 404;
const STATUS_BAD_REQUEST = 400;
const STATUS_OK = 200
const STATUS_SERVER_ERROR = 500

module.exports = {
    STATUS_NOT_FOUND,
    STATUS_BAD_REQUEST,
    STATUS_OK,
    STATUS_SERVER_ERROR
}